document.writeln("	<section class=\"success_case\">");
document.writeln("		<div class=\"p_tle p_tle_sc\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				成功案例 			");
document.writeln("				</h2>");
document.writeln("				<h3>—— 身边的祛斑榜样</h3>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("		<div class=\"p_con p_con_sc\">");
document.writeln("			<ul class=\"sc_out_ul\">");
document.writeln("				<li>");
document.writeln("					<ul class=\"sc_item_ul clearfix\">");
document.writeln("						<li><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/sc_pic_1.jpg\" alt=\"\"></li>");
document.writeln("						<li><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/sc_pic_2.jpg\" alt=\"\"></li>");
document.writeln("					</ul>");
document.writeln("					<div class=\"sc_item_btm bdrds6\">");
document.writeln("						<h4 class=\"sc_item_h4 fnred1\"><strong>崔小姐</strong>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp妊娠斑，重度斑块&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp26岁</h4>");
document.writeln("						<p class=\"sc_item_p\">");
document.writeln("							我现在26岁，脸上的斑从去年生了孩子后起就一发不可收拾。自己下决心去激光祛斑，花了一大笔钱。保持了两个月，色斑又复发了，中间也没晒太阳啊！听朋友说上宫庄还是很有效的，于是就订购了一套。几周后果然变白了。为了验证不会复发，我还故意停用一段时间，斑斑却没有长回来，这下可乐坏我了！");
document.writeln("						</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<ul class=\"sc_item_ul clearfix\">");
document.writeln("						<li><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/sc_pic_3.jpg\" alt=\"\"></li>");
document.writeln("						<li><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/sc_pic_4.jpg\" alt=\"\"></li>");
document.writeln("					</ul>");
document.writeln("					<div class=\"sc_item_btm bdrds6\">");
document.writeln("						<h4 class=\"sc_item_h4 fnred1\"><strong>刘小姐</strong>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp辐射斑，中度斑块&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp32岁</h4>");
document.writeln("						<p class=\"sc_item_p\">");
document.writeln("							分享一下我的祛斑经历，第一张是在小区楼道拍的，那时候我拍照极不自然，分辨率一高就可以看到脸上的斑点。第二张是我用上宫庄几个月后，出游时拍的照片，完全没有用粉底哦。嘻嘻，喜悦的心情不言而喻。");
document.writeln("						</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<ul class=\"sc_item_ul clearfix\">");
document.writeln("						<li><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/sc_pic_5.jpg\" alt=\"\"></li>");
document.writeln("						<li><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/sc_pic_6.jpg\" alt=\"\"></li>");
document.writeln("					</ul>");
document.writeln("					<div class=\"sc_item_btm bdrds6\">");
document.writeln("						<h4 class=\"sc_item_h4 fnred1\"><strong>王小姐</strong>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp雀斑，中度色斑&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp27岁</h4>");
document.writeln("						<p class=\"sc_item_p\">");
document.writeln("							色斑是从09年开始的，那时候天天熬夜对着电脑写论文。有天一照镜子发现脸上长了好多斑块！说是辐射斑，后来几年我涂过美白霜，吃过中药，折腾好几年，大姨妈都折腾得不规律了，最终是上宫庄内调产品彻底祛除了我的斑块。我给大家分享的经验是：1、保证睡眠！2、不要太相信外涂的产品，治标不治本，会复发！3、有效果后就坚持使用！");
document.writeln("						</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>	");
document.writeln("	</section>");
document.writeln("	<!--success caseover-->");
document.writeln("	<!--morder-block-->");
document.writeln("	<section class=\"morder_area\">");
document.writeln("			<a href=\"tel:4000602823\"><div class=\"morder_no\"><span><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/morder_ico.jpg\"/></span>400-060-2823</div></a>");
document.writeln("			<div class=\"morder_stm\">货到付款 | 全国包邮</div>");
document.writeln("			<ul class=\"morder_btn_area clearfix f14\">");
document.writeln("				<li><a href=\"#order\"><span class=\"mordernow_btn bdrds6\">立即订购</span></a></li>");
document.writeln("				<li><a href=\"tel:4000602823\"><span class=\"morderph_btn bdrds6\">电话订购</span></a></li>");
document.writeln("			</ul>");
document.writeln("	</section>");
document.writeln("	<!--morder-blockover-->");
document.writeln("	<!--patchsource -->");
document.writeln("	<section class=\"patch_sous\">");
document.writeln("		<div class=\"p_tle p_tle_ps\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				长斑根源 			");
document.writeln("				</h2>");
document.writeln("				<h3 class=\"p_tle_sh3\">内分泌失调，黑色素代谢缓慢</h3>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("		<div class=\"p_con p_con_ps\">");
document.writeln("			<img class=\"ps_arrows\" src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/psous_arrows.jpg\" width=\"9\" height=\"9\">");
document.writeln("			<ul class=\"ps_ul_t clearfix\">");
document.writeln("				<li>");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/psous_pic_1.jpg\" width=\"117\" height:\"123\">");
document.writeln("					<span>内分泌失调</span>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/psous_pic_2.jpg\" width=\"117\" height:\"123\">");
document.writeln("					<span>新陈代谢缓慢</span>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/psous_pic_3.jpg\" width=\"117\" height:\"123\">");
document.writeln("					<span>黑色素沉积</span>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/psous_pic_4.jpg\" width=\"117\" height:\"123\">");
document.writeln("					<span>形成色斑</span>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<p class=\"ps_p_b bdrds4\">");
document.writeln("				<strong>中医认为</strong>：“有斑必有瘀，治瘀不离血”。即，当人体内分泌失调时，就会导致气血在人体运行不畅，心血以及营养物质无法到达脸部，从而导致细胞新陈代谢缓慢，皮肤中黑色素无法正常排出，长期积累下来，就形成色斑。");
document.writeln("			</p>");
document.writeln("			");
document.writeln("		</div>");
document.writeln("	</section>");
document.writeln("	<!--patchsourceover-->");
document.writeln("");
document.writeln("");
document.writeln("	<!--adjust -->");
document.writeln("	<section class=\"adjust\">");
document.writeln("		<div class=\"p_tle p_tle_ajs\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				内调外养 			");
document.writeln("				</h2>");
document.writeln("				<h3 class=\"p_tle_sh3\">根源祛除色斑</h3>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("		<div class=\"p_con p_con_ajs\">");
document.writeln("			<ul>");
document.writeln("				<li class=\"ajs_item\">");
document.writeln("					<h4 class=\"ajs_item_tle\"><span class=\"bdrds2\">1</span><strong class=\"fnred2\">内部祛斑：</strong>谷胱甘肽调理分泌</h4> ");
document.writeln("					<div class=\"ajs_text_area clearfix\">");
document.writeln("						<img class=\"ajs_img\" src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/adjust_pic_1.jpg\" width=\"103\" height:\"123\">");
document.writeln("						<p class=\"ajs_p\">");
document.writeln("							特有的美白因子—谷胱甘肽，能有效<em>调节内分泌，阻断色斑形成根源</em>，防止黑色素形成；抑制黑色素细胞活性，<em>加速肌肤新陈代谢</em>，从而清除黑色素生长环境。");
document.writeln("						</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li class=\"ajs_item\">");
document.writeln("					<h4 class=\"ajs_item_tle\"><span class=\"bdrds2\">2</span><strong class=\"fnred2\">外部淡斑：</strong>草本因子分解黑色素</h4> ");
document.writeln("					<div class=\"ajs_text_area clearfix\">");
document.writeln("						<img class=\"ajs_img\" src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/adjust_pic_2.jpg\" width=\"103\" height:\"123\">");
document.writeln("						<p class=\"ajs_p\">");
document.writeln("							国际公认强效祛斑成分：熊果叶提取物——熊果苷，能快速<em>分解麦拉宁黑色素</em>，激活细胞活力，使黑色素呈游离状排出；在肌肤表层<em>形成保护膜</em>，增强肌肤抗氧化能力，防止斑点复发。");
document.writeln("						</p>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("");
document.writeln("		</div>");
document.writeln("	</section>");
document.writeln("	<!--adjust over-->");
document.writeln("");
document.writeln("	<!--four_step -->");
document.writeln("	<section class=\"four_step\">");
document.writeln("		<div class=\"p_tle p_tle_fstep\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				调、抑、清、护 			");
document.writeln("				</h2>");
document.writeln("				<h3 class=\"p_tle_sh3\">四步打造无瑕肌肤</h3>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("		<div class=\"p_con p_con_fstep\">");
document.writeln("			<ul class=\"fstep_ul clearfix\">");
document.writeln("				<li class=\"fstep_item\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/fstep_pic_1.jpg\" width=\"110\" height=\"100\">");
document.writeln("					<p>");
document.writeln("						1.调节内分泌，<em>增强人体代谢黑色素能力</em>，并减少黑色素生成。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"fstep_item\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/fstep_pic_2.jpg\" width=\"110\" height=\"100\">");
document.writeln("					<p>");
document.writeln("						2.抑制黑色素形成时期的促黑细胞活性，<em>切断黑色素形成链条</em>。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"fstep_item\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/fstep_pic_3.jpg\" width=\"110\" height=\"100\">");
document.writeln("					<p>");
document.writeln("						3.快速渗透到黑色素聚集区域，<em>分解黑色素</em>，并使其呈游离状排出。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"fstep_item\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/fstep_pic_4.jpg\" width=\"110\" height=\"100\">");
document.writeln("					<p>");
document.writeln("						4.肌肤表层<em>形成保护膜</em>，抵抗外界对皮肤的侵蚀。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</section>");
document.writeln("	<!--four_step over-->");
document.writeln("	<!--morder-block-->");
document.writeln("	<section class=\"morder_area\">");
document.writeln("			<a href=\"tel:4000602823\"><div class=\"morder_no\"><span><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/morder_ico.jpg\"/></span>400-060-2823</div></a>");
document.writeln("			<div class=\"morder_stm\">货到付款 | 全国包邮</div>");
document.writeln("			<ul class=\"morder_btn_area clearfix f14\">");
document.writeln("				<li><a href=\"#order\"><span class=\"mordernow_btn bdrds6\">立即订购</span></a></li>");
document.writeln("				<li><a href=\"tel:4000602823\"><span class=\"morderph_btn bdrds6\">电话订购</span></a></li>");
document.writeln("			</ul>");
document.writeln("	</section>");
document.writeln("	<!--morder-blockover-->");
document.writeln("	<!--threeweek -->");
document.writeln("	<section class=\"three_week\">");
document.writeln("		<div class=\"p_tle p_tle_tweek\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				三周期净斑无瑕		");
document.writeln("				</h2>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("		<div class=\"p_con p_con_tweek\">");
document.writeln("			<ul class=\"tweek_ul\">  ");
document.writeln("				<li class=\"tweek_item clearfix\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/tweek_pic_1.jpg\" width=\"98\" height=\"98\">");
document.writeln("					<h5 class=\"tweek_item_tle\">第一阶段</h5>");
document.writeln("					<p>使用<em>一周期</em>，色斑变浅，边缘开始淡化。</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"tweek_item clearfix\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/tweek_pic_2.jpg\" width=\"98\" height=\"98\">");
document.writeln("					<h5 class=\"tweek_item_tle\">第二阶段</h5>");
document.writeln("					<p>使用<em>两周期</em>，斑块主体明显变淡，斑点消失。</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"tweek_item clearfix\">");
document.writeln("					<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/tweek_pic_3.jpg\" width=\"98\" height=\"98\">");
document.writeln("					<h5 class=\"tweek_item_tle\">第三阶段</h5>");
document.writeln("					<p>使用<em>三周期，色斑彻底消失</em>，肤色净白匀称。</p>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</section>");
document.writeln("	<!--threeweek over-->");
document.writeln("");
document.writeln("	<!--prdshow -->");
document.writeln("	<section class=\"prd_show\">");
document.writeln("		<div class=\"p_tle p_tle_pshow\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				产品展示		");
document.writeln("				</h2>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("			<ul class=\"pshow_suit_box\">");
document.writeln("				<li class=\"pshow_suit_item\">");
document.writeln("					<div class=\"pshow_pic_box1\">");
document.writeln("						<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/pshow_pic_1.jpg\" width=\"211\" height=\"134\">");
document.writeln("					</div>");
document.writeln("						<h4 class=\"pshow_suit_name\"><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/pshow_suit_ico.jpg\" width=\"16\" height=\"16\" >焕颜新生微祛斑基础套装</h4>");
document.writeln("");
document.writeln("					<ul class=\"pshow_prd_line\">");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("					</ul>");
document.writeln("					<ul class=\"pshow_prd_con\">");
document.writeln("						<li class=\"pshow_prd_item\">韩方素白洁颜乳100G*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">韩方素白活肤水120ML*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">韩方素白防护乳100ML</li>");
document.writeln("						<li class=\"pshow_prd_item\">凝皙美白去黄泥膜150G*1</li>");
document.writeln("					</ul>");
document.writeln("					<div style=\"clear:both;\"></div>");
document.writeln("					<div class=\"pshow_prs\">");
document.writeln("						<span><em>特惠价：￥399</em>&nbsp&nbsp专柜价：￥422</span>");
document.writeln("						<a href=\"#order\"  onclick=\"pro_radio(80050)\"><span class=\"pshow_btn bdrds2\">立即订购</span></a>");
document.writeln("					</div>");
document.writeln("					<p>");
document.writeln("						<strong>产品功效：</strong>能够加速黑色素的分解与排出，从而减少皮肤色素沉积，能祛除黄褐斑，晒斑，雀斑等各类色斑，具有均匀肤色、美白保湿的功效。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"pshow_boundary\"></li>");
document.writeln("				<li class=\"pshow_suit_item\">");
document.writeln("					<div class=\"pshow_pic_box2\">");
document.writeln("						<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/pshow_pic_2.jpg\" width=\"211\" height=\"134\">");
document.writeln("					</div>");
document.writeln("						<h4 class=\"pshow_suit_name\"><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/pshow_suit_ico.jpg\" width=\"16\" height=\"16\" >焕颜新生祛斑轻度套装</h4>");
document.writeln("");
document.writeln("					<ul class=\"pshow_prd_line\">");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("					</ul>");
document.writeln("					<ul class=\"pshow_prd_con\">");
document.writeln("						<li class=\"pshow_prd_item\">韩方素白洁颜乳&nbsp&nbsp&nbsp100G*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">韩方素白活肤水&nbsp&nbsp&nbsp120ML*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">韩方素白精华乳&nbsp&nbsp&nbsp20ML*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">凝皙美白去黄泥膜150G*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">珍美软胶囊&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp0.5G*60S*1</li>");
document.writeln("						");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("					</ul>");
document.writeln("					<div style=\"clear:both;\"></div>");
document.writeln("					<div class=\"pshow_prs\">");
document.writeln("						<span><em>特惠价：￥499</em>&nbsp&nbsp专柜价：￥700</span>");
document.writeln("						<a href=\"#order\" onclick=\"pro_radio(207408)\"><span class=\"pshow_btn bdrds2\">立即订购</span></a>");
document.writeln("					</div>");
document.writeln("					<p>");
document.writeln("						<strong>产品功效：</strong>专为日晒斑、辐射斑，有少量色斑及皮肤色素沉淀的人群研发。能快速到达黑色素聚集层，微化、净化肌肤细胞。同时内部调理新陈代谢，平衡内分泌，持久祛斑。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("				<li class=\"pshow_boundary\"></li>");
document.writeln("				<li class=\"pshow_suit_item\">");
document.writeln("					<div class=\"pshow_pic_box3\">");
document.writeln("						<img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/pshow_pic_3.jpg\" width=\"211\" height=\"134\">");
document.writeln("					</div>");
document.writeln("						<h4 class=\"pshow_suit_name\"><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/pshow_suit_ico.jpg\" width=\"16\" height=\"16\" >焕颜新生祛斑中度套装</h4>");
document.writeln("");
document.writeln("					<ul class=\"pshow_prd_line\">");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("						<li></li>");
document.writeln("					</ul>");
document.writeln("					<ul class=\"pshow_prd_con\">");
document.writeln("						<li class=\"pshow_prd_item\">素白洁颜乳100G*1 </li>");
document.writeln("						<li class=\"pshow_prd_item\">素白活肤水120ML*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">素白精华乳20ML*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">素白面霜30G*1</li>");
document.writeln("						<li class=\"pshow_prd_item\">珍美软胶囊0.5G*60S*2</li>");
document.writeln("					</ul>");
document.writeln("					<div style=\"clear:both;\"></div>");
document.writeln("					<div class=\"pshow_prs\">");
document.writeln("						<span><em>特惠价：￥699</em>&nbsp&nbsp专柜价：￥808</span>");
document.writeln("						<a href=\"#order\" onclick=\"pro_radio(80052)\"><span class=\"pshow_btn bdrds2\">立即订购</span></a>");
document.writeln("					</div>");
document.writeln("					<p>");
document.writeln("						<strong>产品功效：</strong>针对雀斑，黄褐斑等斑点研发，外部精准直达黑色素聚集深度，防止其蔓延。内部调节内分泌，进一步促进肌肤代谢，促进黑色素排出。最后在肌肤表层形成保护膜，防止色斑复发。");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("	</section>");
document.writeln("	<!--prdshow over-->");
document.writeln("	<!--morder-block-->");
document.writeln("	<section class=\"morder_area\">");
document.writeln("			<a href=\"tel:4000602823\"><div class=\"morder_no\"><span><img src=\"../../img.jianke.com/jk2013/images/nopic.png\" jk-Src=\"images/morder_ico.jpg\"/></span>400-060-2823</div></a>");
document.writeln("			<div class=\"morder_stm\">货到付款 | 全国包邮</div>");
document.writeln("			<ul class=\"morder_btn_area clearfix f14\">");
document.writeln("				<li><a href=\"#order\"><span class=\"mordernow_btn bdrds6\">立即订购</span></a></li>");
document.writeln("				<li><a href=\"tel:4000602823\"><span class=\"morderph_btn bdrds6\">电话订购</span></a></li>");
document.writeln("			</ul>");
document.writeln("	</section>");
document.writeln("	<!--morder-blockover-->");
document.writeln("");
document.writeln("	<!--expert-->");
document.writeln("	<section class=\"expert\">");
document.writeln("		<div class=\"p_tle p_tle_ept\">");
document.writeln("			<hgroup>");
document.writeln("				<h2>");
document.writeln("				<img class=\"p_tle_sign\" src=\"images/tle_ico.jpg\" width=16 height=16/>	");
document.writeln("				专家问答			");
document.writeln("				</h2>");
document.writeln("			</hgroup>");
document.writeln("		</div>");
document.writeln("		<ul class=\"ept_ul\">");
document.writeln("			<li class=\"ept_item\">");
document.writeln("				<p class=\"ept_ask_p\"><span class=\"bdrds2\">Q</span><strong>【Jojo：】</strong>为什么我怀孕后脸上的斑越来越明显了？</p>");
document.writeln("				<p class=\"ept_asr_p\"><span class=\"bdrds2\">A</span><strong>专家解答：</strong>妇女怀孕后，体内激素水平会发生变化，使黑色素细胞活性增加，黑色素增多。沉着的色素常常于妊娠早、中期间出现，并逐渐加重至足月。大部份患者在分娩后，色斑会持续存在。所以色斑越来越明显。</p>");
document.writeln("			</li>");
document.writeln("			<li class=\"ept_item\">");
document.writeln("				<p class=\"ept_ask_p\"><span class=\"bdrds2\">Q</span><strong>【小饶：】</strong>网上都说激光祛斑比较快，是这样的吗？</p>");
document.writeln("				<p class=\"ept_asr_p\"><span class=\"bdrds2\">A</span><strong>专家解答：</strong>激光祛斑效果虽要快一些，但花费比较高，且激光祛斑后，因皮肤受到能量的点射，因此有红肿现象，甚至有些皮肤比较敏感者有严重的反应。有些激光祛斑后色素尚未全部消退，会造成脸部肤色不均匀，白一块、黑一块。</p>");
document.writeln("			</li>");
document.writeln("			<li class=\"ept_item\">");
document.writeln("				<p class=\"ept_ask_p\"><span class=\"bdrds2\">Q</span><strong>【风筝：】</strong>之前用过的祛斑产品祛完不多久又长回来，你们的产品会不会也这样？</p>");
document.writeln("				<p class=\"ept_asr_p\"><span class=\"bdrds2\">A</span><strong>专家解答：</strong>我们的产品用后不会反弹，因为上宫庄祛斑是内调外祛、恢复调节人体的代谢和生理功能，提高身体免疫机能。清除色斑增强了皮肤代谢功能，抑制了酪氨酸酶活性，消除了色斑，所以真正做到了祛斑不反弹效果。</p>");
document.writeln("			</li>");
document.writeln("			<li class=\"ept_item\">");
document.writeln("				<p class=\"ept_ask_p\"><span class=\"bdrds2\">Q</span><strong>【小不点：】</strong>我是属于遗传雀斑，能祛掉吗？</p>");
document.writeln("				<p class=\"ept_asr_p\"><span class=\"bdrds2\">A</span><strong>专家解答：</strong>雀斑是常见染色体显性遗传性皮肤病，常幼时出现，多见于青少年面、颈、手背等暴露部位。为淡褐色或深褐色斑点，多散在对称分布，具有遗传倾向。春夏加重、秋冬变浅。上宫庄祛斑内含“丽白因子”能迅速涌入肌底，有效抑制皮肤中酪胺酸酶的活性，阻断黑色素的形成，通过自身与酪胺酸酶的结合，加速黑色素的分解与排泄，祛除雀斑。</p>");
document.writeln("			</li>");
document.writeln("			<li class=\"ept_item\">");
document.writeln("				<p class=\"ept_ask_p\"><span class=\"bdrds2\">Q</span><strong>【燕青：】</strong>上宫庄产品祛斑的原理是什么？</p>");
document.writeln("				<p class=\"ept_asr_p\"><span class=\"bdrds2\">A</span><strong>专家解答：</strong>色斑形成主要主要是因为黑色素增多，酪胺酸酵素增高，而上宫庄产品内含有的熊果苷能够有效地抑制皮肤中酪氨酸酶的活性，阻断黑色素的形成，加速黑色素的分解与排泄，从而减少皮肤色素沉积，祛除色斑。以及谷胱甘肽能够紧密地锁住酪氨酸酶，阻止酪氨酸的渗透，以此来达到抑制黑色素形成的目的。风行欧美50年，堪称世纪美白祛斑经典。</p>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</section>");
document.writeln("	<!--expert over-->");